platform :ios, '13.0'

target 'Example' do
  use_frameworks!
  
  # 开发模式：直接使用本地framework源码
  # 这样源码的任何改动都会立即反映在Example项目中
  pod 'RichTextEditorKit', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end